Feature/add clients group tab
alleycorpsur/profitline_front_ts_react-nextjs_web pull request #15
Opened 2024-04-16 12:36 UTC by mercuryeater

En este PR van 179 - 180 y una parte del 201 porque faltaria la solicitud POST de crear el grupo. Adelante van los pnatlallazos delflujo de Grupos de clientes como va.

![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/4c67b6fb-4283-4954-af6d-5fdbd5c27f2e)

![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/593e7e00-9de1-413f-b366-12e8324f714e)

![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/c172b8b9-2c37-4a62-87dc-5fb5c1db54cf)

2024-04-17 15:46 UTC, santiagoPadi requested changes

2024-04-17 15:46 UTC, santiagoPadi commented on src/components/molecules/modals/ModalCreateClientsGroup/ModalCreateClientsGroup.tsx
> +        console.log(selectedRows);
eso es innecesario. console.log jamas en un pr

2024-04-17 15:46 UTC, santiagoPadi commented on src/components/molecules/modals/ModalCreateClientsGroup/ModalCreateClientsGroup.tsx
> +    console.log("Crear Grupo clickeado");
eso es innecesario. console.log jamas en un pr

2024-04-17 15:46 UTC, santiagoPadi commented on src/components/molecules/modals/ModalCreateClientsGroup/ModalCreateClientsGroup.tsx
> +        console.log(group);
eso es innecesario. console.log jamas en un pr

2024-04-17 15:46 UTC, santiagoPadi commented on src/components/molecules/modals/ModalCreateClientsGroup/ModalCreateClientsGroup.tsx
> +            onCreateGroup();
onOk={onCreateGroup};

2024-04-17 15:46 UTC, santiagoPadi commented on src/components/molecules/tables/ClientsGroupsTable/ClientsGroupsTable.tsx
> +// import { Dispatch, SetStateAction } from "react";
si no se una se elimina.

2024-04-17 15:46 UTC, santiagoPadi commented on src/components/molecules/tables/ClientsGroupsTable/ClientsGroupsTable.tsx
> +// import { FilterClients } from "@/components/atoms/FilterClients/FilterClients";
si no se una se elimina.

2024-04-17 15:46 UTC, santiagoPadi commented on src/components/molecules/tables/ClientsGroupsTable/ClientsGroupsTable.tsx
> +  // setIsViewDetailsGroup: Dispatch<
si no se una se elimina.

2024-04-17 15:46 UTC, santiagoPadi commented on src/components/molecules/tables/ClientsGroupsTable/ClientsGroupsTable.tsx
> +  // setIsViewDetailsGroup
si no se una se elimina.

2024-04-17 15:46 UTC, santiagoPadi commented on src/components/molecules/tables/ClientsGroupsTable/ClientsGroupsTable.tsx
> +  // eslint-disable-next-line no-unused-vars
eliminamos esto

2024-04-17 15:46 UTC, santiagoPadi commented on src/components/molecules/tables/ClientsGroupsTable/ClientsGroupsTable.tsx
> +    // shipTo: selectedFilters.shipTo,
si no se una se elimina.

2024-04-17 15:46 UTC, santiagoPadi commented on src/components/molecules/tables/ClientsGroupsTable/ClientsGroupsTable.tsx
> +            {/* <FilterClients /> */}
si no se una se elimina.

2024-04-18 16:14 UTC, mercuryeater commented
Va asi:
![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/de921c21-96d9-4899-864c-3241bfd00512)

![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/cb4422ad-53f8-4964-b2e5-d87bef814593)

![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/05473907-287a-4ba7-a50f-4b0d084918af)

![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/6c02d3ba-1013-465c-9c12-aa23d2c86205)

2024-04-18 16:36 UTC, santiagoPadi approved these changes

2024-04-18 16:36 UTC, merged