Feature/add clients tab api connection
alleycorpsur/profitline_front_ts_react-nextjs_web pull request #23
Opened 2024-04-30 17:12 UTC by mercuryeater

En este PR es para este US https://alleycorpsur.atlassian.net/browse/PROF-127?atlOrigin=eyJpIjoiY2RlYzQzOTNjNzA2NGIxMmIxNWI1ZWM5MmE1YmVkNTMiLCJwIjoiaiJ9

- Entonces Lista los clientes:
![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/401fb7b7-33d7-4347-9d1e-dd25c9e8cc46)

- Hay un Filtro de clientes con los valores dispuestos en el Figma, que genera opciones en base a los clientes
![Detalles Proyecto - Google Chrome 30_04_2024 11_54_57 a  m](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/bf260892-ccbb-4c50-99dc-8ead7e317898)

- Creacion de clientes con los modales de BillingPeriod y Documentos funcionales:
![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/ec69e9aa-464c-4d6d-a699-b2ad19718980)
![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/1cdd1b11-c217-4f3c-b190-fe2de11da2f9)
![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/3e0b3913-b9db-4ec0-8e45-ca2d36e3a5b5)
![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/f83874e4-acfc-4025-a461-0efff6bb4791)

Eso sí, aún no hay una forma clara de comprobar qué documentos se necesitan en especifico (tipo para el tipo 2 RUT, para el tipo 1 Cedula, etc...) por cliente, sino que está de acuerdo al Figma visualmente. 

- PUT de cliente:
![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/19008dca-3fdf-4f9a-a4a2-75f86adbee58)
![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/cd9498c7-a982-49ad-98db-090de50d12e3)
En esta ultima las tarjetas que dicen "seleccionar archivo" funcionan en base a los documentos que llegand el back, pero como no estamos descargando ni leyendo el archivo que viene en una url entonces no accedemos a su nombre, se podría modificar.

- Tambien va la eliminacion del cliente
![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/30123a28-897b-4520-9a1c-e030f99479d9)

2024-04-30 20:05 UTC, mercuryeater commented
Cambia el botón de edición a cancelar y ahora como submit solo funciona el boton de CTA al final del form
![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/f9ee071d-a47e-4645-b19c-a1fde4dc2dc7)
![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/72f9f468-658a-412e-b320-e47058de81a6)

También ahora se usa MessageAPI de ant design cuando se crea y edita un cliente.

2024-05-02 14:41 UTC, mercuryeater commented
El hook hecho por Brayan con nombre **useClients** para traer los **portafolios** de clientes por proyecto **se cambió a usePortfolios**, de manera que ahora el componente **clientsViewTable utiliza es usePortfolios**.

2024-05-02 18:08 UTC, santiagoPadi requested changes

2024-05-02 18:08 UTC, santiagoPadi commented on src/components/atoms/FilterClients/FilterClients.tsx
> +      city: any[];
las ventajas de typescript son typar las cosas no poner any en cualquier lado. 
Usemos las herramientas correctamente

2024-05-02 18:08 UTC, santiagoPadi commented on src/components/atoms/FilterClients/FilterClients.tsx
> +    city: [] as any,
las ventajas de typescript son typar las cosas no poner any en cualquier lado. 
Usemos las herramientas correctamente

2024-05-02 18:08 UTC, santiagoPadi commented on src/components/molecules/selects/clients/SelectBillingPeriod/SelectBillingPeriodDay.tsx
> +  errors: any;
las ventajas de typescript son typar las cosas no poner any en cualquier lado. 
Usemos las herramientas correctamente

2024-05-02 18:08 UTC, santiagoPadi commented on src/components/molecules/selects/clients/SelectBillingPeriod/SelectBillingPeriodOrder.tsx
> +  field?: any;
las ventajas de typescript son typar las cosas no poner any en cualquier lado. 
Usemos las herramientas correctamente

2024-05-02 18:08 UTC, santiagoPadi commented on src/components/molecules/selects/clients/SelectClientTypes/SelectClientTypes.tsx
> +  errors: any;
las ventajas de typescript son typar las cosas no poner any en cualquier lado. 
Usemos las herramientas correctamente

2024-05-02 18:08 UTC, santiagoPadi commented on src/components/molecules/selects/clients/SelectDocumentTypes/SelectDocumentTypes.tsx
> +  errors: any;
las ventajas de typescript son typar las cosas no poner any en cualquier lado. 
Usemos las herramientas correctamente

2024-05-02 18:08 UTC, santiagoPadi commented on src/components/molecules/selects/clients/SelectHoldings/SelectHoldings.tsx
> +interface Props {
esta interfaz la he visto como en 3 archivos. En vez de crearlo varias veces se crea en un archivo de interfaces / tipos (en la carpeta types)

2024-05-02 18:08 UTC, santiagoPadi commented on src/components/molecules/selects/clients/SelectLocations/SelectLocations.tsx
> +interface Props {
otra vez

2024-05-02 18:08 UTC, santiagoPadi commented on src/components/molecules/selects/clients/SelectPaymentConditions/SelectPaymentCondition.tsx
> +interface Props {
again

2024-05-02 18:08 UTC, santiagoPadi commented on src/components/molecules/selects/clients/SelectRadicationTypes/SelectRadicationTypes.tsx
> +interface Props {
6ta vez creo.

2024-05-02 18:08 UTC, santiagoPadi commented on src/components/molecules/selects/clients/SelectRisks/SelectRisks.tsx
> +  errors: any;
7ma

2024-05-02 18:08 UTC, santiagoPadi commented on src/components/molecules/tables/ClientsProjectTable/ClientsProjectTable.tsx
> +    city: [] as any,
las ventajas de typescript son typar las cosas no poner any en cualquier lado. 
Usemos las herramientas correctamente

2024-05-02 18:08 UTC, santiagoPadi commented on src/types/clients/IClients.ts
> +  headers: any;
las ventajas de typescript son typar las cosas no poner any en cualquier lado. 
Usemos las herramientas correctamente

2024-05-02 20:24 UTC, mercuryeater commented on src/components/atoms/DocumentButton/DocumentButton.tsx
> +  // eslint-disable-next-line no-unused-vars
Aunque sea una interface me requiere utilizar el "_", pero se pasa handleDelete directamente al button onClick, entonces no se requiere
```
 <Button
            onClick={handleOnDelete}
            className="deleteDocButton"
            type="text"
            icon={<X size={"20px"} />}
          />
```
Si la quito entonces salta este otro error del eslint;
![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/29f61614-aaf0-44e3-82b4-9dbc9eda6908)

Y si quito la declaración de tipos ahí entonces aparece este
![image](https://github.com/alleycorpsur/profitline_front_ts_react-nextjs_web/assets/79395978/1747ccfd-d4d5-4113-a066-17c70e697ac7)

2024-05-02 20:39 UTC, mercuryeater commented
Va corrección de todo, excepto `DocumentButton.tsx ` por lo mencionado en el comentario

2024-05-03 20:03 UTC, merged